

server.port: 9345

logging:
  level:
    # We turned this off to double-check we're running the correct profile
    org.springframework.jdbc.datasource.init.ScriptUtils: off

spring:
  config:
      import: secrets.yaml
  datasource:
    url: jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.uk-london-1.oraclecloud.com))(connect_data=(service_name=g2e77f48e70267f_practicepokemon_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    username: ${database.user}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
